In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

# Фиксация случайного зерна.
torch.manual_seed(0)

# Создание тензора указанной формы со случайными значениями из интервала [0, 1).
tensor_a = torch.rand(size=(3, 4, 5))

# Проверка: вывод тензора.
tensor_a

tensor([[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
         [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000, 0.1610, 0.2823]],

        [[0.6816, 0.9152, 0.3971, 0.8742, 0.4194],
         [0.5529, 0.9527, 0.0362, 0.1852, 0.3734],
         [0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423]],

        [[0.5263, 0.2437, 0.5846, 0.0332, 0.1387],
         [0.2422, 0.8155, 0.7932, 0.2783, 0.4820],
         [0.8198, 0.9971, 0.6984, 0.5675, 0.8352],
         [0.2056, 0.5932, 0.1123, 0.1535, 0.2417]]])

In [3]:
# 2. Выведите его форму (shape)

# Вывод размерности тензора.
tensor_a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10

# Изменения размерности тензора.
tensor_a.resize_((6, 10))

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000, 0.1610,
         0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852,
         0.3734],
        [0.3051, 0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231,
         0.7423],
        [0.5263, 0.2437, 0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783,
         0.4820],
        [0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123, 0.1535,
         0.2417]])

In [5]:
# 4. Создайте случайный IntTensor размера 10

# Создание тензора указанной формы со случайными целыми числами из интервала [0, 100).
tensor_b = torch.randint(low=0, high=100, size=(10, 1))

# Проверка: вывод тензора.
tensor_b

tensor([[99],
        [26],
        [63],
        [74],
        [75],
        [ 0],
        [18],
        [32],
        [68],
        [12]])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

# Перемножение тензоров.
tensor_a * tensor_b.T

tensor([[49.1294, 19.9738,  5.5741,  9.7703, 23.0567,  0.0000,  8.8217, 28.6862,
         30.9827,  7.5877],
        [34.5405, 10.4446,  1.4065, 12.4956, 22.0416,  0.0000, 12.5580, 25.6004,
         10.9500,  3.3872],
        [67.4792, 23.7950, 25.0173, 64.6875, 31.4556,  0.0000, 17.1493,  1.1573,
         12.5957,  4.4810],
        [30.2049, 24.2320, 11.0823, 19.9677, 11.3010,  0.0000,  3.7463, 29.7536,
         49.1714,  8.9080],
        [52.1033,  6.3351, 36.8293,  2.4533, 10.4038,  0.0000, 14.6784, 25.3811,
         18.9212,  5.7835],
        [81.1583, 25.9237, 44.0018, 41.9984, 62.6432,  0.0000, 10.6771,  3.5951,
         10.4351,  2.9005]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

# Матричное умножение тензора на самого себя.
tensor_a @ tensor_a.T

tensor([[3.0095, 2.2361, 2.4913, 2.7194, 2.2429, 2.3108],
        [2.2361, 1.8997, 2.0007, 1.8061, 1.8508, 1.7467],
        [2.4913, 2.0007, 3.7884, 2.0904, 2.0721, 3.3966],
        [2.7194, 1.8061, 2.0904, 3.0710, 1.9942, 2.1061],
        [2.2429, 1.8508, 2.0721, 1.9942, 2.3609, 1.9992],
        [2.3108, 1.7467, 3.3966, 2.1061, 1.9992, 3.6625]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

# Определение координат точки.
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

# Определение функции.
y = x**3 + z - 75 * t

# Обратный проход для вычисления частных производных.
y.backward()

# Вывод частных производных.
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [9]:
# 8. Создайте единичный тензор размера 5x6

# Создание единичного тензора заданной размерности.
tensor_c = torch.ones(size=(5, 6))

# Проверка: вывод тензора.
tensor_c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy

# Преобразование тензора в матрицу NumPy.
tensor_c = tensor_c.numpy()

# Проверка: вывод матрицы NumPy и её типа.
tensor_c, type(tensor_c)

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=float32),
 numpy.ndarray)